export const  cards = [
    {'id':0,
    'title': 'used space', 
      'icon': 'faCopy', 
      'number': 49,
      'maxNumber': 50, 
      'unit': 'GB',
      'footer': '<a href="#">get more space</a>'},
    {'id':1,
    'title': 'revenue', 
    'icon': 'faCopy', 
    'number': 34245,
    'maxNumber': null, 
    'unit': '$',
    'footer': 'last 24 hours'},
  {'id':2,
  'title': 'fixed issues', 
  'icon': 'faCopy', 
  'number': 75,
  'maxNumber': null, 
  'unit': null,
  'footer': 'tracked from github'},
  {'id':3,
  'title': 'followers', 
  'icon': 'faCopy', 
  'number': 245,
  'maxNumber': null, 
  'unit': '+',
  'footer': 'just updated'}
  ];